### ISSUE TITLE
No way to specify directionality of reads

### ISSUE THREAD

**Issue by conchoecia** [transXpress/transXpress-nextflow#18]
A lot of commonly-used RNA-seq library prep kits produce directional reads where the first read is antisense. Trinity and RNAspades have options to specify the directionality of the reads to help the assembly (`--SS_lib_type RF` in Trinity and `--ss-rf` in RNAspades).

**Comment by photocyte** [comment]
We do have support for this - wasn't fully implemented but now works for both trinity and rnaSPAdes.  It's handled using nextflow profiles currently.

Using the ./run.sh wrapper script, can use the 1st parameter for the assembler, and the 2nd parameter to input the profile:
```
./run.sh trinity strandSpecific_local
```

The "profiles" block in the `nextflow.config` file has the currently available profiles.  It's a bit verbose, and since the mode of execution (local vs cluster) is also handled via the profile, there might be a cleaner/simpler way to handle these types of parameters in the future.

**Comment by photocyte** [comment]
(p.s. didn't mean to close exactly, of course open to any comments on the implementation)
